ls.itpc.ru/Controllers/AutocompleteController.cs
using AccountingUnitCheck.data.Storage;
using AccountingUnitCheck.data.Models;
using AccountingUnitCheck.data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

namespace ls.itpc.ru.Controllers
{
    public class AutocompleteController : Controller
    {
        AddressRepository repo;

        public AutocompleteController()
        {
            repo = new AddressRepository(new AsupContext());
        }

        public ActionResult Index()
        {
            int selectedIndex = 0;

            List<CityModel> cities = repo.GetCities().ToList();
            SelectList selCities = new SelectList(cities, "ID", "City", selectedIndex);
            ViewBag.Cities = selCities;

            List<Street> streets = new List<Street>();
            SelectList selStreets = new SelectList(streets, "ID");
            ViewBag.Streets = selStreets;

            List<House> houses = new List<House>();
            SelectList selHouses = new SelectList(houses, "ID");
            ViewBag.Houses = selHouses;

            List<Flat> flats = new List<Flat>();
            SelectList selFlats = new SelectList(flats, "ID");
            ViewBag.Flats = selFlats;

            return View();
        }

        public ActionResult GetStreetsByCityId(int id)
        {
            IEnumerable<Street> selStreets = repo.GetStreets(id);
            return PartialView(selStreets.OrderBy(x => x.StreetName));
        }

        public ActionResult GetHousesByStreetId(int id)
        {
            IEnumerable<House> selHouses = repo.GetHouses(id);
            return PartialView(selHouses);
        }

        public ActionResult GetFlatsByHouseId(int id)
        {
            IEnumerable<Flat> selFlats = repo.GetFlats(id);
            return PartialView(selFlats);
        }

        public ActionResult GetLschetByFlatId(int id)
        {
            LschetModel selLschet = repo.GetLschet(id);
            return PartialView("GetLschetByFlatId", selLschet);
        }

        public ActionResult GetPassportWorkByHouseId(int id)
        {
            string passportWork = repo.GetPassportWork(id);
            return PartialView("GetPassportWorkByHouseId", passportWork);
        }

        public ActionResult GetUFMSByHouseId(int id)
        {
            string UFMS = repo.GetUFMSByHouseId(id);
            return PartialView("GetUFMSByHouseId", UFMS);
        }

        public ActionResult GetManagementCompanyByLschet(int id)
        {
            string ManagementCompany = repo.GetManagementCompanyByLschet(id);
            return PartialView("GetManagementCompanyByLschet", ManagementCompany);
        }

        public ActionResult GetServicesForLschet(int id)
        {
            string services = repo.GetServicesForLschet(id);
            string[] Services = services.Split(new string[]{","}, StringSplitOptions.RemoveEmptyEntries);
            return PartialView("GetServicesForLschet", Services);
        }
    }
}

ls.itpc.ru/Views/Autocomplete/GetFlatsByHouseId.cshtml
@model IEnumerable<AccountingUnitCheck.data.Models.Flat>


<option selected="selected">Выберите номер квартиры...</option>
@foreach (var item in Model)
{
    <option value="@item.ID">@(item.FlatNumber)</option>
}

ls.itpc.ru/Views/Autocomplete/GetHousesByStreetId.cshtml
@model IEnumerable<AccountingUnitCheck.data.Models.House>

<option selected="selected">Выберите номер дома...</option>
@foreach (var item in Model)
{
    <option value="@item.ID">@(item.HouseNumber)</option>
}

ls.itpc.ru/Views/Autocomplete/GetLschetByFlatId.cshtml
@model AccountingUnitCheck.data.Models.LschetModel

<input type="hidden" id="lschetHidden" value="@Model.ID" />
<div id="lschet">
    <h3>Лицевой счет:</h3>    
    @if (Model == null)
    {
        <div class="danger">Лицевой счет не найден!</div>
    }
    else
    {
        <div class="form-group">@Model.Lschet</div>
    }
    
</div>

ls.itpc.ru/Views/Autocomplete/GetManagementCompanyByLschet.cshtml
@model string

<div id="ManagementCompany">
    <h3>Управляющая компания:</h3>
    @if (@Model == null)
    {
        <div class="form-group">Не найдена</div>
    }
    else
    {
        <div class="form-group">@Model</div>
    }
</div>

ls.itpc.ru/Views/Autocomplete/GetPassportWorkByHouseId.cshtml
@model string

<div id="PassportWork">
    <h3>Паспортная работа:</h3>
    @if (@Model == null)
    {
        <div class="form-group">Не ведется</div>
    }
    else
    {
        <div class="form-group">@Model</div>
    }
</div>

ls.itpc.ru/Views/Autocomplete/GetServicesForLschet.cshtml
@model IEnumerable<string>

<div id="Services">
    
    <h3>Услуги:</h3>
    @if (Model.Contains("11"))
    {
        <span class="icon-utbattery gi-3x text-success" title="Центральное отопление"></span>
    }
    else
    {
        <span class="icon-utbattery gi-3x text-muted" title="Центральное отопление"></span>
    }

    @if (Model.Contains("750"))
    {
        <span class="icon-uthouse gi-3x text-success" title="Капремонт"></span>

    }
    else
    {
        <span class="icon-uthouse gi-3x text-muted" title="Капремонт"></span>

    }

    @if (Model.Contains("383") || Model.Contains("384") || Model.Contains("546"))
    {
        <span class="icon-utelectricity gi-3x text-success" title="Электроэнергия"></span>
    }
    else
    {
        <span class="icon-utelectricity gi-3x text-muted" title="Электроэнергия"></span>
    }

    @if (Model.Contains("10") || Model.Contains("8"))
    {
        <span class="icon-utcrane gi-3x text-success" title="Водоснабжение"></span>
    }
    else
    {
        <span class="icon-utcrane gi-3x text-muted" title="Водоснабжение"></span>
    }

    @if (Model.Contains("1355") || Model.Contains("1455") || Model.Contains("1328") || Model.Contains("1416") || Model.Contains("4"))
    {
        <span class="icon-utcleaner gi-3x text-success" title="Жилищные услуги"></span>

    }
    else
    {
        <span class="icon-utcleaner gi-3x text-muted" title="Жилищные услуги"></span>

    }

    @if (Model.Contains("701"))
    {
        <span class="icon-utpassport gi-3x text-success" title="Услуги паспортного стола"></span>

    }
    else
    {
        <span class="icon-utpassport gi-3x text-muted" title="Услуги паспортного стола"></span>
    }
</div>

ls.itpc.ru/Views/Autocomplete/GetStreetsByCityId.cshtml
@using AccountingUnitCheck.data
@model IEnumerable<AccountingUnitCheck.data.Models.Street>

@foreach (var item in Model)
{
    <option value="@item.ID">@item.StreetName</option>
}

ls.itpc.ru/Views/Autocomplete/GetUFMSByHouseId.cshtml
@model string

<div id="UFMS">
    <h3>Отдел ФМС:</h3>
    @if (Model == null)
    {
        <div class="form-group">Не найден</div>
    }
    else
    { 
        <div class="form-group">@Model</div>
    }
</div>

ls.itpc.ru/Views/Autocomplete/Index.cshtml
@{
    ViewBag.Title = "ITPC help";
}
<script src="~/Scripts/ScriptsForAutocomplete/CreateAutocomplete.js"></script>
<link href="~/Content/style.css" rel="stylesheet" />
<link href="~/Content/fontsizing.css" rel="stylesheet" />
<div class="ui-widget">
    <h3>Выберите город</h3>
    @Html.DropDownList("City", ViewBag.Cities as SelectList, "Выберите город...", new { id = "city" })
</div>

<div class="ui-widget">
    <h3>Выберите улицу</h3>
    @Html.DropDownList("Street", ViewBag.Streets as SelectList, new { id = "street" })
</div>

<div class="ui-widget">
    <h3>Выберите номер дома</h3>
    @Html.DropDownList("House", ViewBag.Houses as SelectList, new { id = "house" })
</div>
<div class="ui-widget">
    <h3>Выберите квартиру</h3>
    @Html.DropDownList("Flat", ViewBag.Flats as SelectList, new { id = "flat" })
</div>
    <br />
    <br />
    <button id="showLschet">Показать лицевой счет</button>

    <br />
    <div class="form-inline">
        <div id="lschet"></div>
        <div id="PassportWork"></div>
        <div id="UFMS"></div>
        <div id="ManagementCompany"></div>
        <div id="Services"></div>
    </div>
<script src="~/Scripts/Site.js"></script>

ls.itpc.ru/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Scripts/ScriptsForAutocomplete/jquery-ui.css" />
    <script src="~/Scripts/ScriptsForAutocomplete/jquery.js"></script>
    <script src="~/Scripts/ScriptsForAutocomplete/jquery-ui.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                                       
                </button>
                @Html.ActionLink("Поиск лицевого счета", "Index", "Autocomplete", new { area = "" }, new { @class = "navbar-brand" })   
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Поиск лицевого счета v1.0", "Index", "Home")</li>
                    <li>@Html.ActionLink("Поиск лицевого счета v1.1", "Index", "Autocomplete")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Тюменский расчетно-информационный центр</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>